name: HappyGhastBoost
main: dev.arzor.happyghastboost.HappyGhastBoost
version: 1.0.0
api-version: 1.21
author: ArZor
description: Boost system for Happy Ghast mounts

commands:
  happyghastboost:
    description: Manage HappyGhastBoost (logging and reload)
    aliases: [hgb]
    usage: /<command> <logdisable|logbasic|logdebug|logverbose|reload>
    permission: happyghastboost.admin
    permission-message: You do not have permission to use this command.

permissions:
  happyghastboost.admin:
    description: Allows use of admin commands like /happyghastboost debug|reload|verbose
    default: op

  happyghastboost.use:
    description: Allows the player to use Happy Ghast boost features
    default: false

    # 🎚️ Preset Permissions (examples only — optional to define)
    # These are just sample entries to help permission tools (like LuckPerms) recognize them.
    # You can add as many custom presets as you want in config.yml (e.g. "legendary", "trial", etc.).
    # Format: happyghastboost.preset.<preset-name>
    happyghastboost.preset.vip:
      description: Applies the 'vip' boost preset from config.yml
      default: false

    happyghastboost.preset.ultra:
      description: Applies the 'ultra' boost preset from config.yml
      default: false